apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tahseen-app

resources:
  - namespace.yaml
  - api.yaml
  - worker.yaml
  - redis.yaml
  - web-ui.yaml

images:
  - name: kandlagifari/tahseen-api
    newTag: latest
  - name: kandlagifari/tahseen-worker
    newTag: latest
  - name: kandlagifari/tahseen-web-ui
    newTag: latest
