apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tahseen-checker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kandlagifari/tahseen-opentelemetry.git
    targetRevision: main
    path: k8s/app
  destination:
    server: https://kubernetes.default.svc
    namespace: tahseen-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
